stages:
  - run
 

build-test:
  stage: run
  image: maven:3.9.6-eclipse-temurin-21
  script:
    # Étape 1 : Build et lancement du service part1
    - cd mgl7230_tp3_part1
    - mvn clean install 
    - cd service
    - nohup mvn exec:java &  # Lancer le service part1 en arrière-plan

    # Étape 2 : Build et lancement du service part2
    - cd ../../mgl7230_tp3_part2
    - mvn clean install 
    - cd service
    - nohup mvn exec:java &  # Lancer le service part2 en arrière-plan

    # Attendre un peu pour s'assurer que les services démarrent
    - sleep 10

    # Étape 3 : Build de la partie 3
    - cd ../../mgl7230_tp3_part3
    - mvn clean install

  
  artifacts:
    paths:
      - mgl7230_tp3_part1/service/target/
      - mgl7230_tp3_part2/service/target/
    expire_in: 1 hour

