stages:
  - build
  - start_services


build-services:
  stage: build
  image: maven:3.9.6-eclipse-temurin-21
  script:
    - cd mgl7230_tp3_part1
    - mvn clean install 
    - cd ../mgl7230_tp3_part2
    - mvn clean install 
  artifacts:
    paths:
      - mgl7230_tp3_part1/service/target/
      - mgl7230_tp3_part2/service/target/
    expire_in: 1 hour


run-services:
  stage: start_services
  image: maven:3.9.6-eclipse-temurin-21
  script:
    - cd mgl7230_tp3_part1
    - nohup mvn exec:java &
    - cd ../mgl7230_tp3_part2
    - nohup mvn exec:java &
    - sleep 05
  artifacts:
    name: "services-logs"
    paths:
      - nohup.out
  when: on_success    